# Proses Cleaning Data

# File CSV

In [24]:
!ls -lh compact.csv

-rw-r--r-- 1 root root 161M Feb 28 06:14 compact.csv

In [25]:
df_dea = pd.read_csv('compact.csv')

In [26]:
len(df_dea)

567120

In [27]:
df_dea.head(10)

,country,date,total_cases,new_cases,new_cases_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths,new_deaths,...,population,population_density,median_age,life_expectancy,gdp_per_capita,extreme_poverty,diabetes_prevalence,handwashing_facilities,hospital_beds_per_thousand,human_development_index
0,Afghanistan,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,40578847.0,62.215549,16.752001,65.616997,1516.273315,NaN,10.9,51.938343,0.39,NaN
1,Afghanistan,2020-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,40578847.0,62.215549,16.752001,65.616997,1516.273315,NaN,10.9,51.938343,0.39,NaN
2,Afghanistan,2020-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,40578847.0,62.215549,16.752001,65.616997,1516.273315,NaN,10.9,51.938343,0.39,NaN
3,Afghanistan,2020-01-04,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,...,40578847.0,62.215549,16.752001,65.616997,1516.273315,NaN,10.9,51.938343,0.39,NaN
4,Afghanistan,2020-01-05,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,...,40578847.0,62.215549,16.752001,65.616997,1516.273315,NaN,10.9,51.938343,0.39,NaN
5,Afghanistan,2020-01-06,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,...,40578847.0,62.215549,16.752001,65.616997,1516.273315,NaN,10.9,51.938343,0.39,NaN
6,Afghanistan,2020-01-07,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,...,40578847.0,62.215549,16.752001,65.616997,1516.273315,NaN,10.9,51.938343,0.39,NaN
7,Afghanistan,2020-01-08,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,...,40578847.0,62.215549,16.752001,65.616997,1516.273315,NaN,10.9,51.938343,0.39,NaN
8,Afghanistan,2020-01-09,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,40578847.0,62.215549,16.752001,65.616997,1516.273315,NaN,10.9,51.938343,0.39,NaN
9,Afghanistan,2020-01-10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,40578847.0,62.215549,16.752001,65.616997,1516.273315,NaN,10.9,51.938343,0.39,NaN

In [39]:
pd.set_option('display.max_seq_items', None)
pd.set_option('display.max_rows', None)

In [40]:
df_dea['country'].unique()

<ArrowStringArray>
[                                        'Afghanistan',
                                              'Africa',
                                             'Albania',
                                             'Algeria',
                                      'American Samoa',
                                             'Andorra',
                                              'Angola',
                                            'Anguilla',
                                 'Antigua and Barbuda',
                                           'Argentina',
                                             'Armenia',
                                               'Aruba',
                                                'Asia',
                                    'Asia excl. China',
                                           'Australia',
                                             'Austria',
                                          'Azerbaijan',
                                             'Bahamas',
                                             'Bahrain',
                                          'Bangladesh',
                                            'Barbados',
                                             'Belarus',
                                             'Belgium',
                                              'Belize',
                                               'Benin',
                                             'Bermuda',
                                              'Bhutan',
                                             'Bolivia',
                     'Bonaire Sint Eustatius and Saba',
                              'Bosnia and Herzegovina',
                                            'Botswana',
                                              'Brazil',
                              'British Virgin Islands',
                                              'Brunei',
                                            'Bulgaria',
                                        'Burkina Faso',
                                             'Burundi',
                                            'Cambodia',
                                            'Cameroon',
                                              'Canada',
                                          'Cape Verde',
                                      'Cayman Islands',
                            'Central African Republic',
                                                'Chad',
                                               'Chile',
                                               'China',
                                            'Colombia',
                                             'Comoros',
                                               'Congo',
                                        'Cook Islands',
                                          'Costa Rica',
                                       'Cote d'Ivoire',
                                             'Croatia',
                                                'Cuba',
                                             'Curacao',
                                              'Cyprus',
                                             'Czechia',
                        'Democratic Republic of Congo',
                                             'Denmark',
                                            'Djibouti',
                                            'Dominica',
                                  'Dominican Republic',
                                          'East Timor',
                                             'Ecuador',
                                               'Egypt',
                                         'El Salvador',
                                             'England',
                                   'England and Wales',
                                   'Equatorial Guinea',
                                             'Eritrea',
                                             'Estonia',
                                            'Eswatini',
                                            'Ethiopia',
                                              'Europe',
                                 'European Union (27)',
                                    'Falkland Islands',
                                       'Faroe Islands',
                                                'Fiji',
                                             'Finland',
                                              'France',
                                       'French Guiana',
                                    'French Polynesia',
                                               'Gabon',
                                              'Gambia',
                                             'Georgia',
                                             'Germany',
                                               'Ghana',
                                           'Gibraltar',
                                              'Greece',
                                           'Greenland',
                                             'Grenada',
                                          'Guadeloupe',
                                                'Guam',
                                           'Guatemala',
                                            'Guernsey',
                                              'Guinea',
                                       'Guinea-Bissau',
                                              'Guyana',
                                               'Haiti',
                               'High-income countries',
                                            'Honduras',
                                           'Hong Kong',
                                             'Hungary',
                                             'Iceland',
                                               'India',
                                           'Indonesia',
                                                'Iran',
                                                'Iraq',
                                             'Ireland',
                                         'Isle of Man',
                                              'Israel',
                                               'Italy',
                                             'Jamaica',
                                               'Japan',
                                              'Jersey',
                                              'Jordan',
                                          'Kazakhstan',
                                               'Kenya',
                                            'Kiribati',
                                              'Kosovo',
                                              'Kuwait',
                                          'Kyrgyzstan',
                                                'Laos',
                                              'Latvia',
                                             'Lebanon',
                                             'Lesotho',
                                             'Liberia',
                                               'Libya',
                                       'Liechtenstein',
                                           'Lithuania',
                                'Low-income countries',
                       'Lower-middle-income countries',
                                          'Luxembourg',
                                               'Macao',
                                          'Madagascar',
                                              'Malawi',
                                            'Malaysia',
                                            'Maldives',
                                                'Mali',
                                               'Malta',
                                    'Marshall Islands',
                                          'Martinique',
                                          'Mauritania',
                                           'Mauritius',
                                             'Mayotte',
                                              'Mexico',
                                'Micronesia (country)',
                                             'Moldova',
                                              'Monaco',
                                            'Mongolia',
                                          'Montenegro',
                                          'Montserrat',
                                             'Morocco',
                                          'Mozambique',
                                             'Myanmar',
                                             'Namibia',
                                               'Nauru',
                                               'Nepal',
                                         'Netherlands',
                                       'New Caledonia',
                                         'New Zealand',
                                           'Nicaragua',
                                               'Niger',
                                             'Nigeria',
                                                'Niue',
                                       'North America',
                                         'North Korea',
                                     'North Macedonia',
                                    'Northern Ireland',
                            'Northern Mariana Islands',
                                              'Norway',
                                             'Oceania',
                                                'Oman',
                                            'Pakistan',
                                               'Palau',
                                           'Palestine',
                                              'Panama',
                                    'Papua New Guinea',
                                            'Paraguay',
                                                'Peru',
                                         'Philippines',
                                            'Pitcairn',
                                              'Poland',
                                            'Portugal',
                                         'Puerto Rico',
                                               'Qatar',
                                             'Reunion',
                                             'Romania',
                                              'Russia',
                                              'Rwanda',
                                    'Saint Barthelemy',
                                        'Saint Helena',
                               'Saint Kitts and Nevis',
                                         'Saint Lucia',
                          'Saint Martin (French part)',
                           'Saint Pierre and Miquelon',
                    'Saint Vincent and the Grenadines',
                                               'Samoa',
                                          'San Marino',
                               'Sao Tome and Principe',
                                        'Saudi Arabia',
                                            'Scotland',
                                             'Senegal',
                                              'Serbia',
                                          'Seychelles',
                                        'Sierra Leone',
                                           'Singapore',
                           'Sint Maarten (Dutch part)',
                                            'Slovakia',
                                            'Slovenia',
                                     'Solomon Islands',
                                             'Somalia',
                                        'South Africa',
                                       'South America',
                                         'South Korea',
                                         'South Sudan',
                                               'Spain',
                                           'Sri Lanka',
                                               'Sudan',
                                'Summer Olympics 2020',
                                            'Suriname',
                                              'Sweden',
                                         'Switzerland',
                                               'Syria',
                                              'Taiwan',
                                          'Tajikistan',
                                            'Tanzania',
                                            'Thailand',
                                                'Togo',
                                             'Tokelau',
                                               'Tonga',
                                        'Transnistria',
                                 'Trinidad and Tobago',
                                             'Tunisia',
                                              'Turkey',
                                        'Turkmenistan',
                            'Turks and Caicos Islands',
                                              'Tuvalu',
                                              'Uganda',
                                             'Ukraine',
                                'United Arab Emirates',
                                      'United Kingdom',
                                       'United States',
                        'United States Virgin Islands',
                       'Upper-middle-income countries',
                                             'Uruguay',
                                          'Uzbekistan',
                                             'Vanuatu',
                                             'Vatican',
                                           'Venezuela',
                                             'Vietnam',
                                               'Wales',
                                   'Wallis and Futuna',
                                      'Western Sahara',
                                'Winter Olympics 2022',
                                               'World',
                                   'World excl. China',
                   'World excl. China and South Korea',
 'World excl. China, South Korea, Japan and Singapore',
                                               'Yemen',
                                              'Zambia',
                                            'Zimbabwe']
Length: 262, dtype: str

In [42]:
pd.reset_option('display.max_seq_items')
pd.reset_option('display.max_rows')

In [45]:
isocode_kosong = df_dea['code'].isna()
print(isocode_kosong)

0         False
1         False
2         False
3         False
4         False
          ...
567115    False
567116    False
567117    False
567118    False
567119    False
Name: code, Length: 567120, dtype: bool

In [46]:
isocode_owid = df_dea['code'].astype(str).str.startswith('OWID_')
print(isocode_owid)

0         False
1         False
2         False
3         False
4         False
          ...
567115    False
567116    False
567117    False
567118    False
567119    False
Name: code, Length: 567120, dtype: bool

In [48]:
df_non_negara = df_dea[isocode_kosong | isocode_owid]

In [50]:
df_non_negara['country'].unique().tolist()

['Africa',
 'Asia',
 'Asia excl. China',
 'England',
 'England and Wales',
 'Europe',
 'European Union (27)',
 'High-income countries',
 'Kosovo',
 'Low-income countries',
 'Lower-middle-income countries',
 'North America',
 'Northern Ireland',
 'Oceania',
 'Scotland',
 'South America',
 'Summer Olympics 2020',
 'Transnistria',
 'Upper-middle-income countries',
 'Wales',
 'Winter Olympics 2022',
 'World',
 'World excl. China',
 'World excl. China and South Korea',
 'World excl. China, South Korea, Japan and Singapore']

In [51]:
hapus_data = ['Africa',
 'Asia',
 'Asia excl. China',
 'England',
 'England and Wales',
 'Europe',
 'European Union (27)',
 'High-income countries',
 'Kosovo',
 'Low-income countries',
 'Lower-middle-income countries',
 'North America',
 'Northern Ireland',
 'Oceania',
 'Scotland',
 'South America',
 'Summer Olympics 2020',
 'Transnistria',
 'Upper-middle-income countries',
 'Wales',
 'Winter Olympics 2022',
 'World',
 'World excl. China',
 'World excl. China and South Korea',
 'World excl. China, South Korea, Japan and Singapore']

In [52]:
df_clean = df_dea[~df_dea['country'].isin(hapus_data)].copy()

In [53]:
df_clean.head(10)

,country,date,total_cases,new_cases,new_cases_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths,new_deaths,...,population,population_density,median_age,life_expectancy,gdp_per_capita,extreme_poverty,diabetes_prevalence,handwashing_facilities,hospital_beds_per_thousand,human_development_index
0,Afghanistan,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,40578847.0,62.215549,16.752001,65.616997,1516.273315,NaN,10.9,51.938343,0.39,NaN
1,Afghanistan,2020-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,40578847.0,62.215549,16.752001,65.616997,1516.273315,NaN,10.9,51.938343,0.39,NaN
2,Afghanistan,2020-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,40578847.0,62.215549,16.752001,65.616997,1516.273315,NaN,10.9,51.938343,0.39,NaN
3,Afghanistan,2020-01-04,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,...,40578847.0,62.215549,16.752001,65.616997,1516.273315,NaN,10.9,51.938343,0.39,NaN
4,Afghanistan,2020-01-05,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,...,40578847.0,62.215549,16.752001,65.616997,1516.273315,NaN,10.9,51.938343,0.39,NaN
5,Afghanistan,2020-01-06,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,...,40578847.0,62.215549,16.752001,65.616997,1516.273315,NaN,10.9,51.938343,0.39,NaN
6,Afghanistan,2020-01-07,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,...,40578847.0,62.215549,16.752001,65.616997,1516.273315,NaN,10.9,51.938343,0.39,NaN
7,Afghanistan,2020-01-08,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,...,40578847.0,62.215549,16.752001,65.616997,1516.273315,NaN,10.9,51.938343,0.39,NaN
8,Afghanistan,2020-01-09,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,40578847.0,62.215549,16.752001,65.616997,1516.273315,NaN,10.9,51.938343,0.39,NaN
9,Afghanistan,2020-01-10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,40578847.0,62.215549,16.752001,65.616997,1516.273315,NaN,10.9,51.938343,0.39,NaN

In [56]:
df_clean.info()

<class 'pandas.DataFrame'>
Index: 522849 entries, 0 to 567119
Data columns (total 61 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   country                                     522849 non-null  str
 1   date                                        522849 non-null  str
 2   total_cases                                 516896 non-null  float64
 3   new_cases                                   513012 non-null  float64
 4   new_cases_smoothed                          511888 non-null  float64
 5   total_cases_per_million                     516896 non-null  float64
 6   new_cases_per_million                       513012 non-null  float64
 7   new_cases_smoothed_per_million              511888 non-null  float64
 8   total_deaths                                516896 non-null  float64
 9   new_deaths                                  514023 non-null  float64
 10  new_deaths_smoothed                         512896 non-null  float64
 11  total_deaths_per_million                    516896 non-null  float64
 12  new_deaths_per_million                      514023 non-null  float64
 13  new_deaths_smoothed_per_million             512896 non-null  float64
 14  excess_mortality                            13663 non-null   float64
 15  excess_mortality_cumulative                 13663 non-null   float64
 16  excess_mortality_cumulative_absolute        13663 non-null   float64
 17  excess_mortality_cumulative_per_million     13663 non-null   float64
 18  hosp_patients                               35442 non-null   float64
 19  hosp_patients_per_million                   35442 non-null   float64
 20  weekly_hosp_admissions                      19666 non-null   float64
 21  weekly_hosp_admissions_per_million          19666 non-null   float64
 22  icu_patients                                34825 non-null   float64
 23  icu_patients_per_million                    34825 non-null   float64
 24  weekly_icu_admissions                       10993 non-null   float64
 25  weekly_icu_admissions_per_million           10993 non-null   float64
 26  stringency_index                            201664 non-null  float64
 27  reproduction_rate                           182734 non-null  float64
 28  total_tests                                 79199 non-null   float64
 29  new_tests                                   75300 non-null   float64
 30  total_tests_per_thousand                    79199 non-null   float64
 31  new_tests_per_thousand                      75300 non-null   float64
 32  new_tests_smoothed                          103580 non-null  float64
 33  new_tests_smoothed_per_thousand             103580 non-null  float64
 34  positive_rate                               101169 non-null  float64
 35  tests_per_case                              100259 non-null  float64
 36  total_vaccinations                          66557 non-null   float64
 37  people_vaccinated                           62365 non-null   float64
 38  people_fully_vaccinated                     60346 non-null   float64
 39  total_boosters                              42285 non-null   float64
 40  new_vaccinations                            52286 non-null   float64
 41  new_vaccinations_smoothed                   185954 non-null  float64
 42  total_vaccinations_per_hundred              66557 non-null   float64
 43  people_vaccinated_per_hundred               62365 non-null   float64
 44  people_fully_vaccinated_per_hundred         60346 non-null   float64
 45  total_boosters_per_hundred                  42285 non-null   float64
 46  new_vaccinations_smoothed_per_million       185954 non-null  float64
 47  new_people_vaccinated_smoothed              185954 non-null  float64
 48  new_people_vaccinated_smoothed_per_hundred  185954 non-null  float64
 49  code                                        522849 non-null  str
 50  continent                                   522849 non-null  str
 51  population                                  520621 non-null  float64
 52  population_density                          513937 non-null  float64
 53  median_age                                  520621 non-null  float64
 54  life_expectancy                             520621 non-null  float64
 55  gdp_per_capita                              427847 non-null  float64
 56  extreme_poverty                             359450 non-null  float64
 57  diabetes_prevalence                         465759 non-null  float64
 58  handwashing_facilities                      266593 non-null  float64
 59  hospital_beds_per_thousand                  332389 non-null  float64
 60  human_development_index                     0 non-null       float64
dtypes: float64(57), str(4)
memory usage: 262.3 MB

In [57]:
kolom_analisis = [
    'continent', 'country', 'date', 'population',
    'total_cases', 'new_cases', 'total_deaths', 'new_deaths',
    'new_vaccinations', 'stringency_index', 'reproduction_rate',
    'gdp_per_capita', 'hospital_beds_per_thousand', 'total_deaths_per_million',
    'people_fully_vaccinated_per_hundred', 'new_deaths_smoothed_per_million',
    'median_age', 'diabetes_prevalence'
]

In [58]:
df_final = df_clean[kolom_analisis].copy()

In [59]:
df_final = df_final.rename(columns={'country': 'location'})

In [60]:
missing_percentages = (df_final.isnull().sum() / len(df_clean)) * 100
missing_percentages = missing_percentages.sort_values(ascending=False)

print("Persentase Missing Values tiap kolom:\n")
print(missing_percentages.head(20))

Persentase Missing Values tiap kolom:

new_vaccinations                       89.999790
people_fully_vaccinated_per_hundred    88.458236
reproduction_rate                      65.050330
stringency_index                       61.429782
hospital_beds_per_thousand             36.427343
gdp_per_capita                         18.170064
diabetes_prevalence                    10.919023
new_deaths_smoothed_per_million         1.903609
new_cases                               1.881423
new_deaths                              1.688059
total_deaths_per_million                1.138570
total_cases                             1.138570
total_deaths                            1.138570
population                              0.426127
median_age                              0.426127
continent                               0.000000
location                                0.000000
date                                    0.000000
dtype: float64

In [61]:
df_final = df_final.fillna(0)

In [62]:
df_final.isnull().sum().sum()

np.int64(0)

In [74]:
missing_percentages = (df_final.isnull().sum() / len(df_clean)) * 100
missing_percentages = missing_percentages.sort_values(ascending=False)

print("Persentase Missing Values tiap kolom:\n")
print(missing_percentages.head(20))

Persentase Missing Values tiap kolom:

continent                              0.0
location                               0.0
date                                   0.0
population                             0.0
total_cases                            0.0
new_cases                              0.0
total_deaths                           0.0
new_deaths                             0.0
new_vaccinations                       0.0
stringency_index                       0.0
reproduction_rate                      0.0
gdp_per_capita                         0.0
hospital_beds_per_thousand             0.0
total_deaths_per_million               0.0
people_fully_vaccinated_per_hundred    0.0
new_deaths_smoothed_per_million        0.0
median_age                             0.0
diabetes_prevalence                    0.0
dtype: float64

In [70]:
df_final['date'] = pd.to_datetime(df_final['date'])

In [71]:
df_final['date'] = df_final['date'].dt.strftime('%Y-%m-%d')

In [72]:
df_final['date'].head()

0    2020-01-01
1    2020-01-02
2    2020-01-03
3    2020-01-04
4    2020-01-05
Name: date, dtype: str

In [73]:
df_final[['date', 'new_cases']].dtypes

date             str
new_cases    float64
dtype: object

In [75]:
kolom_deaths = [
    'continent', 'location', 'date', 'population',
    'total_cases', 'new_cases', 'total_deaths', 'new_deaths',
    'reproduction_rate', 'stringency_index'
]
df_CovidDeaths = df_final[kolom_deaths].copy()

In [76]:
kolom_vaccinations = [
    'continent', 'location', 'date', 'population',
    'new_vaccinations', 'people_fully_vaccinated_per_hundred',
    'gdp_per_capita', 'hospital_beds_per_thousand',
    'median_age', 'diabetes_prevalence'
]
df_CovidVaccinations = df_final[kolom_vaccinations].copy()

In [81]:
df_CovidDeaths['date'] = pd.to_datetime(df_CovidDeaths['date'])

In [83]:
df_CovidVaccinations['date'] = pd.to_datetime(df_CovidVaccinations['date'])

# Menyimpan File CSV

In [87]:
df_CovidDeaths.to_csv('CovidDeaths.csv', index=False)
df_CovidVaccinations.to_csv('CovidVaccinations.csv', index=False)

print("\nSukses! File 'CovidDeaths.csv' dan 'CovidVaccinations.csv' sudah siap diunduh.")

Sukses! File 'CovidDeaths.csv' dan 'CovidVaccinations.csv' sudah siap diunduh.

In [85]:
df_CovidDeaths.head()

,continent,location,date,population,total_cases,new_cases,total_deaths,new_deaths,reproduction_rate,stringency_index
0,Asia,Afghanistan,2020-01-01,40578847.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Asia,Afghanistan,2020-01-02,40578847.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Asia,Afghanistan,2020-01-03,40578847.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Asia,Afghanistan,2020-01-04,40578847.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Asia,Afghanistan,2020-01-05,40578847.0,0.0,0.0,0.0,0.0,0.0,0.0

In [86]:
df_CovidDeaths.info()

<class 'pandas.DataFrame'>
Index: 522849 entries, 0 to 567119
Data columns (total 10 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   continent          522849 non-null  str
 1   location           522849 non-null  str
 2   date               522849 non-null  datetime64[us]
 3   population         522849 non-null  float64
 4   total_cases        522849 non-null  float64
 5   new_cases          522849 non-null  float64
 6   total_deaths       522849 non-null  float64
 7   new_deaths         522849 non-null  float64
 8   reproduction_rate  522849 non-null  float64
 9   stringency_index   522849 non-null  float64
dtypes: datetime64[us](1), float64(7), str(2)
memory usage: 52.3 MB

In [79]:
df_CovidVaccinations.info()

<class 'pandas.DataFrame'>
Index: 522849 entries, 0 to 567119
Data columns (total 10 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   continent                            522849 non-null  str
 1   location                             522849 non-null  str
 2   date                                 522849 non-null  str
 3   population                           522849 non-null  float64
 4   new_vaccinations                     522849 non-null  float64
 5   people_fully_vaccinated_per_hundred  522849 non-null  float64
 6   gdp_per_capita                       522849 non-null  float64
 7   hospital_beds_per_thousand           522849 non-null  float64
 8   median_age                           522849 non-null  float64
 9   diabetes_prevalence                  522849 non-null  float64
dtypes: float64(7), str(3)
memory usage: 57.3 MB